name: build

on: [push, pull_request]

env:
  # color output for Pytest
  PYTEST_ADDOPTS: "--color=yes"
  PY_COLORS: 1

permissions:
  contents: read

jobs:
  test:
    name: Test - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }} & PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade PDM to latest version
        run: pdm self update

      - name: Install dependencies
        run: pdm install

      - name: Run tests
        run: pdm run pytest

  deploy:
    name: Deploy
    environment: Deployment
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref=='refs/heads/main' && github.event_name!='pull_request'

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Check release
        id: check_release
        run: |
          python -m pip install build dunamai httpx tomlkit twine
          python -m pip install --index-url https://test.pypi.org/simple/ autopub
          autopub check

      - name: Publish
        if: ${{ steps.check_release.outputs.autopub_release=='true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          autopub prepare
          autopub commit
          autopub build
          autopub githubrelease

      - name: Upload package to PyPI
        if: ${{ steps.check_release.outputs.autopub_release=='true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
